ViewModels/CreateRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperKurs.ViewModels
{
    public class CreateRoleViewModel
    {

        [Required]
        public string RoleName { get; set; }

    }
}

ViewModels/EditUserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperKurs.ViewModels
{
    public class EditUserViewModel
    {

        public EditUserViewModel()
        {

            Claims = new List<string>(); Roles = new List<string>();

        }


        public string Id { get; set; }


        [Required]
        public string UserName { get; set; }

        [Required][EmailAddress]
        public string Email { get; set; }

        public string City { get; set; }

        public List<string> Claims { get; set; }

        public List<string> Roles { get; set; }

    }
}

Controllers/AdministrationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SuperKurs.Models;
using SuperKurs.Utilities;
using SuperKurs.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SuperKurs.Controllers
{

    [Authorize(Policy = "AdminRolePolicy")]
    public class AdministrationController : Controller
    {


            private readonly RoleManager<IdentityRole> roleManager;
            private readonly UserManager<ApplicationUser> userManager;
            private readonly ILogger<AdministrationController> logger;

        public AdministrationController (RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager, ILogger<AdministrationController> logger)
        {

                this.roleManager = roleManager;
                this.userManager = userManager;
                this.logger = logger;
        }



        [HttpGet]
        public async Task<IActionResult> ManageUserClaims(string userId)
        {

            var user = await userManager.FindByIdAsync(userId);
            if(user == null)
            {

                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found.";
                return View("NotFound");

            }

            var existingUserClaims = await userManager.GetClaimsAsync(user);

            var model = new UserClaimsViewModel()
            {
                UserId = user.Id
            };

            foreach (Claim claim in ClaimsStore.AllClaims)
            {

                UserClaim userClaim = new UserClaim
                {
                    ClaimType = claim.Type
                };

                if(existingUserClaims.Any(c => c.Type == claim.Type && c.Value == "true"))
                {
                    userClaim.IsSelected = true;
                }
                model.Cliams.Add(userClaim);
            }
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> ManageUserClaims(UserClaimsViewModel model)
        {

            var user = await userManager.FindByIdAsync(model.UserId);

            if (user == null)
            {

                ViewBag.ErrorMessage = $"User with Id = {model.UserId} cannot be found.";
                return View("NotFound");

            }

            var claims = await userManager.GetClaimsAsync(user);
            var result = await userManager.RemoveClaimsAsync(user, claims);

            if (!result.Succeeded)
            {

                ModelState.AddModelError("", "Cannot remove existing claims");
                return View(model);
            }

            result = await userManager.AddClaimsAsync(user, model.Cliams.Select(c => new Claim(c.ClaimType, c.IsSelected ? "true" : "false")));

            if (!result.Succeeded)
            {

                ModelState.AddModelError("", "Cannot add selected claims to user");
                return View(model);

            }

            return RedirectToAction("EditUser", new { Id = model.UserId});
            
        }


        [HttpGet]
        public async Task<IActionResult> ManageUserRoles(string userId)
        {

            ViewBag.userId = userId;

            var user = await userManager.FindByIdAsync(userId);

            if(user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("Error");
            }

            var model = new List<UserRolesViewModel>();

            foreach(var role in roleManager.Roles)
            {
                var userRolesViewModel = new UserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name,
                    
                };

                if(await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.IsSelected = true;
                }else
                {
                    userRolesViewModel.IsSelected = false;
                }

                model.Add(userRolesViewModel);

            }

            return View(model);

        }


        [HttpPost]
        public async Task<IActionResult> ManageUserRoles(List<UserRolesViewModel> model, string userId)
        {

            ViewBag.userId = userId;

            var user = await userManager.FindByIdAsync(userId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("Error");
            }

            var roles = await userManager.GetRolesAsync(user);
            var result = await userManager.RemoveFromRolesAsync(user, roles);

            if (!result.Succeeded)
            {

                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }

            result = await userManager.AddToRolesAsync(user, model.Where(x => x.IsSelected).Select(y => y.RoleName));

            if (!result.Succeeded)
            {

                ModelState.AddModelError("", "Cannot add selected roles");
                return View(model);
            }

            return RedirectToAction("EditUser", new { Id = userId});

        }



        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {

            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {

                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");

            }
            else
            {

                var result = await userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }

                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("ListUsers");

            }
        }


        [HttpPost]
        [Authorize(Policy = "DeleteRolePolicy")]
        public async Task<IActionResult> DeleteRole(string id)
        {

            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {

                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");

            }
            else
            {

                try
                {
                    var result = await roleManager.DeleteAsync(role);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("ListRoles");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }

                    return View("ListRoles");

                }catch(DbUpdateException ex)
                {

                    logger.LogError($"Error deleting role {ex}");
                    ViewBag.ErrorTitle = $"{role.Name} role is in use";
                    ViewBag.ErrorMessage = $"{role.Name} role cannot be deleted as there are users in this role, please remove the users from the role and then try to delete.";

                    return View("Error");
                }

            }
        }


        [HttpGet]
        public IActionResult ListUsers()
        {

            var users = userManager.Users;
            return View(users);

        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {

            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }

            var userClaims = await userManager.GetClaimsAsync(user);
            var userRoles = await userManager.GetRolesAsync(user);

            var model = new EditUserViewModel();

            model.Id = user.Id;
            model.Email = user.Email;
            model.UserName = user.UserName;
            model.City = user.City;
            model.Claims = userClaims.Select(c => c.Type + " : " + c.Value).ToList();
            model.Roles = (List<string>)userRoles;

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel model)
        {

            var user = await userManager.FindByIdAsync(model.Id);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {

                user.Email = model.Email;
                user.UserName = model.UserName;
                user.City = model.City;

                var result = await userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }

                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);

            }


        }


        [HttpGet]
        public IActionResult CreateRole()
        {


                return View();

        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {

            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };

Views/Administration/AccessDenied.cshtml
<div class="text-center">

    <h1 class="text-danger">Access Denied</h1>
    <h6 class="text-danger">You do not have permission to view this resource.</h6>
    <img src="~/images/noaccess.png" style="height:300px; width:300px" />

</div>

Views/Administration/CreateRole.cshtml
@model CreateRoleViewModel

@{ ViewBag.Title = "Create new role";}


<h1>@ViewBag.Title</h1>

<div class="row">

    <div class="col-md-12">

        <form method="post">

            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">

                <label asp-for="RoleName"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>

            </div>

            <button class="btn btn-primary" type="submit">Create role</button>

        </form>

    </div>

</div>

Views/Administration/Edit.cshtml
@model EditRoleViewModel

@{
    ViewBag.Title = "Edit role";
}

<h1>@ViewBag.Title</h1>

<form method="post" class="mt-3">


    <div class="form-group row">

        <label asp-for="Id" class="col-sm-2 col-form-label"></label>

        <div class="col-sm-10">

            <input asp-for="Id" disabled class="form-control" />

        </div>

    </div>

    <div class="form-group row">

        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>

        <div class="col-sm-10">

            <input asp-for="RoleName" class="form-control" />
            <span asp-validation-for="RoleName" class="text-danger"></span>

        </div>

    </div>


    <div asp-validation-summary="All" class="text-danger">

    </div>


    <div class="form-group row">

        <div class="col-sm-10">

            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-action="ListRoles" class="btn btn-primary">Cancel</a>

        </div>

    </div>


    <div class="card">

        <div class="card-header">

            <h3>Users in this role</h3>

        </div>

        <div class="card-body">

            @if (Model.Users.Any())
            {
                foreach (var user in Model.Users)
                {
                    <h5 class="card-title">@user</h5>
                }

            }
            else
            {
                <h5 class="card-title">None</h5>
            }

        </div>

        <div class="card-footer">

            <a asp-action="EditUsersInRole" asp-controller="Administration" asp-route-roleId="@Model.Id" class="btn btn-primary" style="width:auto">Add or remove users</a>

        </div>

    </div>


</form>

Views/Administration/EditUser.cshtml
@model EditUserViewModel
@{ 
    ViewBag.Title = "Edit user";
}

<h1>Edit user</h1>

<form class="mt-3" method="post">

    <div class="form-group row">

        <label asp-for="Id" class="col-sm-2 col-form-label"></label>

        <div class="col-sm-10">

            <input asp-for="Id" disabled class="form-control">

        </div>

    </div>


    <div class="form-group row">

        <label asp-for="Email" class="col-sm-2 col-form-label"></label>

        <div class="col-sm-10">

            <input asp-for="Email" class="form-control">

            <span asp-validation-for="Email" class="text-danger"></span>

        </div>

    </div>


    <div class="form-group row">

        <label asp-for="UserName" class="col-sm-2 col-form-label"></label>

        <div class="col-sm-10">

            <input asp-for="UserName" class="form-control">

            <span asp-validation-for="UserName" class="text-danger"></span>

        </div>

    </div>


    <div class="form-group row">

        <label asp-for="City" class="col-sm-2 col-form-label"></label>

        <div class="col-sm-10">

            <input asp-for="City" class="form-control">

        </div>

    </div>


    <div asp-validation-summary="All" class="text-danger"></div>


    <div class="form-group row">

        <div class="col-sm-10">

            <button type="submit" class="btn btn-primary">Update</button>

            <a asp-action="ListUsers" class="btn btn-primary">Cancel</a>

        </div>

    </div>


    <div class="card">
        <div class="card-header">
            <h3>User Roles</h3>
        </div>
        <div class="card-body">
            @if (Model.Roles.Any())
            {
                foreach (var role in Model.Roles)
                {
                    <h5 class="card-title">@role</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="ManageUserRoles" asp-route-userId="@Model.Id" style="width:auto" class="btn btn-primary">
                Manage Roles
            </a>
        </div>
    </div>

    <div class="card mt-3">
        <div class="card-header">
            <h3>User Claims</h3>
        </div>
        <div class="card-body">
            @if (Model.Claims.Any())
            {
                foreach (var claim in Model.Claims)
                {
                    <h5 class="card-title">@claim</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="ManageUserClaims" asp-route-userId="@Model.Id"
               style="width:auto" class="btn btn-primary">
                Manage Claims
            </a>
        </div>
    </div>

</form>

Views/Administration/EditUsersInRole.cshtml
@model List<UserRoleViewModel>

@{
    var roleId = ViewBag.roleId;
}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Add or remove users from this role</h2>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].UserId" />
                    <input type="hidden" asp-for="@Model[i].UserName" />
                    <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].IsSelected">
                        @Model[i].UserName
                    </label>
                </div>
            }
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary"
                   style="width:auto" />
            <a asp-action="Edit" asp-route-id="@roleId"
               class="btn btn-primary" style="width:auto">Cancel</a>
        </div>
    </div>
</form>

Views/Administration/ListRoles.cshtml
@model IEnumerable<IdentityRole>
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService authorizationService

@{
    ViewBag.Title = "All roles";
}

<h1>@ViewBag.Title</h1>

@if (Model.Any())
{


    <a asp-controller="administration" asp-action="CreateRole" class="btn btn-primary mb-3" style="width:auto">

        Create role

    </a>

    foreach (var role in Model)
    {


        <div class="card mb-3">

            <div class="card-header">

                Role Id: @role.Id

            </div>

            <div class="card-body">

                <h5 class="card-title">

                    @role.Name

                </h5>

            </div>

            <div class="card-footer">

                <form method="post" asp-action="DeleteRole" asp-route-id="@role.Id">


                    @if((await authorizationService.AuthorizeAsync(User, "EditRolePolicy")).Succeeded)
                    {
                    <a class="btn btn-primary" asp-controller="Administration" asp-action="Edit" asp-route-id="@role.Id">Edit</a>
                    }


                    <span id="confirmDeleteSpan_@role.Id" style="display:none">

                        <span>Are you sure you want to delete this role?</span>
                        <button type="submit" class="btn btn-danger" style="width:auto">Yes</button>
                        <a href="#" class="btn btn-primary" onclick="confirmDelete('@role.Id', false)">No</a>

                    </span>

                    <span id="deleteSpan_@role.Id">

                        <a href="#" class="btn btn-danger" onclick="confirmDelete('@role.Id', true)">Delete</a>

                    </span>


                </form>

            </div>



        </div>

    }

}
else
{

    <div class="card">

        <div class="card-header">

            No roles created yet

        </div>

        <div class="card-body">

            <h5 class="card-title">Use button below to create a role</h5>

            <a asp-controller="administration" asp-action="CreateRole" class="btn btn-primary" style="width:auto">

                Create role

            </a>

        </div>

    </div>

}


@section Scripts{

    <script src="~/js/CustomScript.js"></script>

}

Views/Administration/ListUsers.cshtml
@model IEnumerable<SuperKurs.Utilities.ApplicationUser>

@{
    ViewBag.Title = "All users";
}

<h1>@ViewBag.Title</h1>

@if (Model.Any())
{

    <a class="btn btn-primary" style="width:auto" asp-action="Register" asp-controller="Account">Add new user</a>

    foreach (var user in Model)
    {

    <div class="card mb-3">

        <div class="card-header">

            User Id: @user.Id

        </div>

        <div class="card-body">

            <h5 class="card-title">@user.UserName</h5>

        </div>

        <div class="card-footer">

            <form method="post" asp-action="DeleteUser" asp-route-id="@user.Id"> 

                <a class="btn btn-danger" style="width:auto" asp-controller="Administration" asp-action="EditUser" asp-route-id="@user.Id" >Edit</a>


                <span id="confirmDeleteSpan_@user.Id" style="display:none">
                 
                    <span>Are you sure you want to delete this user?</span>
                    <button type="submit" class="btn btn-danger" style="width:auto">Yes</button>
                    <a href="#" class="btn btn-primary" onclick="confirmDelete('@user.Id', false)">No</a>
                
                </span>

                <span id="deleteSpan_@user.Id">

                    <a href="#" class="btn btn-danger" onclick="confirmDelete('@user.Id', true)">Delete</a>

                </span>


            </form>

        </div>

    </div>

    }

}
else
{

    <div class="card">

        <div class="card-header">

            No users created yet

        </div>

        <div class="card-body">

            <h5>Use the button below to creat new user</h5>

        </div>

        <div class="card-footer">

            <a class="btn btn-primary" style="width:auto" asp-action="Register" asp-controller="Account">Add new user</a>

        </div>

    </div>

}

@section Scripts{ 

    <script src="~/js/CustomScript.js"></script>

}

Views/Administration/ManageUserClaims.cshtml
@model UserClaimsViewModel

<form method="post">

    <div class="card">

        <div class="card-header">

            <h2>Manage user claims</h2>

        </div>

        <div class="card-body">

            @for (int i = 0; i< Model.Cliams.Count; i++)
            {

                <div class="form-check m-1">

                    <input type="hidden" asp-for="@Model.Cliams[i].ClaimType" />
                    <input asp-for="@Model.Cliams[i].IsSelected" class="form-check-input">
                    <label class="form-check-label" asp-for="@Model.Cliams[i].IsSelected">@Model.Cliams[i].ClaimType</label>

                </div>

            }

            <div asp-validation-summary="All" class="text-danger"></div>
        
        </div>

        <div class="card-footer">

            <input type="submit" value="Update" class="btn btn-primary" style="width:auto" />
            <a asp-action="EditUser" asp-route-id="@Model.UserId" class="btn btn-primary" style="width:auto">Cancel</a>

        </div>

</div>

</form>

Views/Administration/ManageUserRoles.cshtml
@model List<UserRolesViewModel>

@{ 
    var userId = ViewBag.userId;
}


<form method="post">

    <div class="card">

        <div class="card-header">

            <h2>Manage user roles</h2>

        </div>

        <div class="card-body">

            @for(int i = 0; i < Model.Count; i++)
            {

            <div class="form-check m-1">

                <input type="hidden" asp-for="@Model[i].RoleId" />
                <input type="hidden" asp-for="@Model[i].RoleName" />
                <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                <label class="form-check-label" asp-for="@Model[i].IsSelected">@Model[i].RoleName</label>

            </div>

            }

        </div>

        <div class="card-footer">

            <input type="submit" value="Update" class="btn btn-primary" style="width:auto" />
            <a asp-action="EditUser" asp-route-id="@userId" class="btn btn-primary" style="width:auto">Cancel</a>

        </div>

    </div>

</form>